[package]
name = "kx"
version = "0.1.0"
authors = ["max"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skim = "0.6.8"
serde_json = "1.0.40"
serde = { version = "1.0.101", features=["derive"] }
itertools = "0.8.0"
